### ISSUE TITLE
panflute removes too much content

### ISSUE THREAD

**Issue by ffel** [sergiocorreia/panflute#135] opened 2020-03-30 09:46 UTC
I have isolated an issue in the following code:

```py
import sys
import panflute as pf

def eprint(*args, **kwargs):
    '''
    print messages (debug info) to stderr
    '''
    print(*args, file=sys.stderr, **kwargs)

def prepare(doc):
    doc.remove = False

def action(elem, doc):
    # purpose: remove 1st level sections and all its contents till you hit
    # a level 2 section.
    if isinstance(elem, pf.Header) and elem.level == 1:
        doc.remove = True
    elif isinstance(elem, pf.Header) and elem.level == 2:
        doc.remove = False

    # unfortunately, text of 2nd header is removed
    if doc.remove:
        return []

    eprint(elem)

def finalize(doc):
    pass

def main(doc=None):
    return pf.run_filter(action,
                         prepare=prepare,
                         finalize=finalize,
                         doc=doc) 

if __name__ == '__main__':
    main()
```

With `context.txt` being the following input

```markdown
Foo
===

bar

Baz
---
```

And when I run `pandoc` accordingly:

```sh
$ pandoc --filter=./bug.py content.txt --out out.txt
```

I would have expected:

```markdown
Baz
---
```

However, I get:

```markdown
 {#baz}
```

I see that the second section header is read by the filter but that it's header contents is empty.
I expect that `pandoc` sets an empty header (so, no text is underlined) with the label `#baz` set explicitly. In the final run the section with the empty label is not recognized as a header and the text `{#baz}` appears in the text.

Is there a bug, or is is something I'm doing wrong? (Otherwise, a nice piece of software!).

cheers

Chris

**Comment by ffel** [comment] 2020-03-30 10:19
Some more experimenting: changed the code above a little (no removes, eprint all elements):

```sh
$ pandoc --filter=./bug.py content.txt --out out.txt
MetaMap()
Str(Foo)
Header(Str(Foo); level=1, identifier='foo')
Str(bar)
Para(Str(bar))
Str(Baz)
Header(Str(Baz); level=2, identifier='baz')
Doc
```

You see `Baz` is first seen as a `Str` (and removed accordingly), only then is is part of `Header`.

Should `Baz` be seen as a `Str`?

**Comment by ffel** [comment] 2020-03-30 14:27
I have found a solution in my real application: I do not remove all elements, I only remove instances of `pf.Block`: this means I can identify a block as a Header and stop removing contents.

**Comment by ickc** [comment] 2020-11-05 12:13
I think the problem is you're modifying doc.remove. And when walking to the next element, that persists.

**Comment by ickc** [comment] 2020-11-05 12:15
I'm closing it now and let us know if that didn't resolve your issue.

**Closed by ickc** 2020-11-05 12:15 UTC
