### ISSUE TITLE
convert_text does not work with tags

### ISSUE THREAD

**Issue by yasserhussain1110** [sergiocorreia/panflute#33] opened 2016-12-13 12:10 UTC
```python
convert_text('<https://www.google.com>')
```

does not work and gives this error 
```sh
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.4/dist-packages/panflute/tools.py", line 176, in convert_text
  out = json.loads(out, object_pairs_hook=from_json)
File "/usr/lib/python3.4/json/__init__.py", line 331, in loads
  return cls(**kw).decode(s)
File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
  obj, end = self.scan_once(s, idx)
File "/usr/local/lib/python3.4/dist-packages/panflute/elements.py", line 1393, in from_json
  return Link(*c[1], url=c[2][0], title=c[2][1], **_decode_ica(c[0]))
IndexError: list index out of range

```

Even though pandoc converts it to -
```sh
<p><a href="https://www.google.com">https://www.google.com</a></p>
```

**Comment by sergiocorreia** [comment] 2016-12-13 20:46
I can't reproduce it using Python 3.5 and panflute 1.6.9 ; which version of Panflute are you using?

```
>>> from panflute import *
>>> convert_text('<https://www.google.com>')

[Para(Link(Str(https://www.google.com); url='https://www.google.com'))]
```

**Comment by sergiocorreia** [comment] 2016-12-13 21:17
Also, can you run `shutil.which('pandoc')` on Python and see what version of Pandoc is Python picking up? (sometimes you may have more than one binary installed)

**Comment by yasserhussain1110** [comment] 2016-12-14 10:17
```sh
pandoc 1.12.2.1
panflute 1.7.1
Python 3.4.3
```

This is most likely pandoc older version issue.  On newer versions of pandoc (1.19) it works properly.

**Comment by sergiocorreia** [comment] 2016-12-14 16:11
Great, closing it now!

**Closed by sergiocorreia** 2016-12-14 16:11 UTC
Labels: bug
